### ISSUE TITLE
fs-extra not found

### ISSUE THREAD

**Issue by true62** [Seamusmario/BonziWORLD-Revived#2] opened 2021-03-19 18:00 UTC
fs-extra model is not found, meaning it throws a error, fs prob fix it i guess lol

**Comment by true62** [comment] 2021-03-19 18:04
fs works a split second, throws error.

**Comment by true62** [comment] 2021-03-19 18:18
fs doesn't work

**Comment by Seamusmario** [comment] 2021-03-19 22:40
did you run npm install in the server folder when you extracted it?

**Comment by true62** [comment] 2021-03-19 23:02
ye

**Comment by Seamusmario** [comment] 2021-04-05 16:31
try removing the package.json file, and then run it again

**Comment by melkwastaken** [comment] 2021-04-06 04:53
still unworking
try importing the old bwr thing

**Comment by Seamusmario** [comment] 2021-04-10 12:11
..right
might archive this until i fix the issue

**Comment by Seamusmario** [comment] 2021-06-06 20:36
Might be fixed in the latest update. Let me know if it doesn't work still

**Closed by Seamusmario** 2021-06-06 20:36 UTC

**Comment by mario999-stack** [comment] 2021-06-14 03:07
The issue is still here:
Error: Cannot find module 'fs-extra'
Require stack:
- C:\Users\David\BonziWORLD-Revived\bwr_server\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:730:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:957:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\David\BonziWORLD-Revived\bwr_server\index.js:6:12)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1068:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:933:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\David\\BonziWORLD-Revived\\bwr_server\\index.js'←[39m ]
}

**Comment by Seamusmario** [comment] 2021-06-14 03:39
install fs-extra

**Comment by mario999-stack** [comment] 2021-06-14 14:10
it cant:
Error: Cannot find module 'express'
Require stack:
- C:\Users\David\BonziWORLD-Revived\bwr_server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\David\BonziWORLD-Revived\bwr_server\index.js:35:15)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\David\\BonziWORLD-Revived\\bwr_server\\index.js' ]
}

**Comment by Seamusmario** [comment] 2021-06-14 15:21
you clearly didn't do "npm install"

**Comment by mario999-stack** [comment] 2021-06-16 14:13
well i did

**Comment by mario999-stack** [comment] 2021-06-16 14:13
give me a min
